### ISSUE TITLE
Missing documentation & status

### ISSUE THREAD

**Issue by xseven** [rqlite/rqlite-cpp#1]
Good day. 
I'd like to checkout a status of this library whether it's fully functional bridge from cpp to rqlite?

And any chance documentation will come up any time soon?

Cheers

**Comment by otoolep** [comment]
It's nowhere near functional unfortunately. I can't give a data when it would be complete. However the rqlite API is quite easy to use, and creating a C/C++ client should be quite straightforward for those familiar with making HTTP requests via C/C++.

**Comment by xseven** [comment]
Thanks, good luck then
